version: "3"
services:
  influxdb:
    image: influxdb:1.8-alpine
    environment:
      INFLUXDB_DB: rails_vue_influxdb_example_development
      INFLUXDB_ADMIN_USER: root
      INFLUXDB_ADMIN_PASSWORD: root
    ports:
      - "8086:8086"
  mysqldb:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
networks:
  default:
    external:
      name: rails_vue_influxdb_example-network
